
- name: Automating Deployment
  github_webhook:
    repository: Ansible-Playbook-Test
    github_url: https://github.com/
    content_type: form
    insecure_ssl: true
    secret: "{{ github_secret }}"
    url: https://d1e56a87d3f1.ngrok.io
    events:
      - push
    user: "{{ github_user }}"
    token: "{{ github_token }}"
  register: deployment

- debug:
    msg: "{{ deployment }}"
